import { Property } from "./game.model";

export const MONOPOLY_PROPERTIES: Property[] = [
    {id: 1, name: 'Badstraße', assetId: 1, color: "brown", mortageValue: 30,  amountColorProperties: 2, developable: true},
    {id: 3, name: 'Turmstraße', assetId: 2, color: "brown", mortageValue: 30, amountColorProperties: 2, developable: true},
    {id: 5, name: 'Südbahnhof', assetId: 23, mortageValue: 100, developable: false},
    {id: 6, name: 'Chauseestraße',assetId: 3, color: "baby blue", mortageValue: 50, amountColorProperties: 3, developable: true},
    {id: 8, name: 'Elisenstraße', assetId: 4, color: "baby blue", mortageValue: 50, amountColorProperties: 3, developable: true},
    {id: 9, name: 'Poststraße', assetId: 5, color: "baby blue", mortageValue: 60, amountColorProperties: 3, developable: true},
    {id: 11, name: 'Seestraße', assetId: 6, color: "pink", mortageValue: 70, amountColorProperties: 3, developable: true},
    {id: 12, name: 'Elektrizitätswerk', assetId:27, mortageValue: 75, developable: false},
    {id: 13, name: 'Hafenstraße', assetId: 7, color: "pink", mortageValue: 70, amountColorProperties: 3, developable: true},
    {id: 14, name: 'Neue Straße', assetId: 8, color: "pink", mortageValue: 80, amountColorProperties: 3, developable: true},
    {id: 15, name: 'Westbahnhof', assetId: 24, mortageValue: 100, developable: false},
    {id: 16, name: 'Münchener Straße', assetId: 9, color: "orange", mortageValue: 90, amountColorProperties: 3, developable: true},
    {id: 18, name: 'Wiener Straße', assetId: 10, color: "orange", mortageValue: 90, amountColorProperties: 3, developable: true},
    {id: 19, name: 'Berliner Straße', assetId: 11, color: "orange", mortageValue: 100, amountColorProperties: 3, developable: true},
    {id: 21, name: 'Theaterstraße', assetId: 12, color: "red", mortageValue: 110, amountColorProperties: 3, developable: true},
    {id: 23, name: 'Museumstraße', assetId: 13, color: "red", mortageValue: 110, amountColorProperties: 3, developable: true},
    {id: 24, name: 'Opernplatz', assetId: 14, color: "red", mortageValue: 120, amountColorProperties: 3, developable: true},
    {id: 25, name: 'Nordbahnhof', assetId: 25, mortageValue: 100, developable: false},
    {id: 26, name: 'Lessingstraße', assetId: 15, color: "yellow", mortageValue: 130, amountColorProperties: 3, developable: true},
    {id: 27, name: 'Schillerstraße', assetId: 16, color: "yellow", mortageValue: 130, amountColorProperties: 3, developable: true},
    {id: 28, name:  'Wasserwerk', assetId: 28, mortageValue: 75, developable: false},
    {id: 29, name: 'Goethestraße', assetId: 17, color: "yellow", mortageValue: 140, amountColorProperties: 3, developable: true},
    {id: 31, name: 'Rathausplatz', assetId: 18, color: "green", mortageValue: 150, amountColorProperties: 3, developable: true},
    {id: 32, name: 'Hauptstraße', assetId: 19, color: "green", mortageValue: 150, amountColorProperties: 3, developable: true},
    {id: 34, name: 'Bahnhofstraße', assetId: 20, color: "green", mortageValue: 160, amountColorProperties: 3, developable: true},
    {id: 35, name: 'Hauptbahnhof', assetId: 26, mortageValue: 100, developable: false},
    {id: 37, name: 'Parkstraße', assetId: 21, color: "blue", mortageValue: 175, amountColorProperties: 2, developable: true},
    {id: 39, name: 'Schlossallee', assetId: 22, color: "blue", mortageValue: 200, amountColorProperties: 2, developable: true}
]