import { Property } from "./game.model";

export const MONOPOLY_PROPERTIES: Property[] = [
    {id: 1, name: 'Badstraße', assetId: 1, color: "brown", amountColorProperties: 2, developable: true},
    {id: 3, name: 'Turmstraße', assetId: 2, color: "brown", amountColorProperties: 2, developable: true},
    {id: 5, name: 'Südbahnhof', assetId: 23, developable: false},
    {id: 6, name: 'Chauseestraße',assetId: 3, color: "baby blue", amountColorProperties: 3, developable: true},
    {id: 8, name: 'Elisenstraße', assetId: 4, color: "baby blue", amountColorProperties: 3, developable: true},
    {id: 9, name: 'Poststraße', assetId: 5, color: "baby blue", amountColorProperties: 3, developable: true},
    {id: 11, name: 'Seestraße', assetId: 6, color: "pink", amountColorProperties: 3, developable: true},
    {id: 12, name: 'Elektrizitätswerk', assetId:27, developable: false},
    {id: 13, name: 'Hafenstraße', assetId: 7, color: "pink", amountColorProperties: 3, developable: true},
    {id: 14, name: 'Neue Straße', assetId: 8, color: "pink", amountColorProperties: 3, developable: true},
    {id: 15, name: 'Westbahnhof', assetId: 24, developable: false},
    {id: 16, name: 'Münchener Straße', assetId: 9, color: "orange", amountColorProperties: 3, developable: true},
    {id: 18, name: 'Wiener Straße', assetId: 10, color: "orange", amountColorProperties: 3, developable: true},
    {id: 19, name: 'Berliner Straße', assetId: 11, color: "orange", amountColorProperties: 3, developable: true},
    {id: 21, name: 'Theaterstraße', assetId: 12, color: "red", amountColorProperties: 3, developable: true},
    {id: 23, name: 'Museumstraße', assetId: 13, color: "red", amountColorProperties: 3, developable: true},
    {id: 24, name: 'Opernplatz', assetId: 14, color: "red", amountColorProperties: 3, developable: true},
    {id: 25, name: 'Nordbahnhof', assetId: 25, developable: false},
    {id: 26, name: 'Lessingstraße', assetId: 15, color: "yellow", amountColorProperties: 3, developable: true},
    {id: 27, name: 'Schillerstraße', assetId: 16, color: "yellow", amountColorProperties: 3, developable: true},
    {id: 28, name:  'Wasserwerk', assetId: 28, developable: false},
    {id: 29, name: 'Goethestraße', assetId: 17, color: "yellow", amountColorProperties: 3, developable: true},
    {id: 31, name: 'Rathausplatz', assetId: 18, color: "green", amountColorProperties: 3, developable: true},
    {id: 32, name: 'Hauptstraße', assetId: 19, color: "green", amountColorProperties: 3, developable: true},
    {id: 34, name: 'Bahnhofstraße', assetId: 20, color: "green", amountColorProperties: 3, developable: true},
    {id: 35, name: 'Hauptbahnhof', assetId: 26, developable: false},
    {id: 37, name: 'Parkstraße', assetId: 21, color: "blue", amountColorProperties: 2, developable: true},
    {id: 39, name: 'Schlossallee', assetId: 22, color: "blue", amountColorProperties: 2, developable: true}
]